# Generated by Django 5.0.3 on 2024-03-29 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('reason', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_catalog.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_catalog.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_catalog.track')),
            ],
        ),
    ]
